In [ ]:
import numpy as np

### Creating arrays

In [2]:
a = np.array([(1.5, 2, 3), (4, 5, 6)])
a.shape

(2, 3)

In [3]:
print(a)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [4]:
a.reshape(6,1).shape

(6, 1)

In [5]:
b = np.arange(6).reshape(2, 3)
b.shape

(2, 3)

In [6]:
a[None,:,:].shape

(1, 2, 3)

In [7]:
c = np.array([a, b])
c.shape

(2, 2, 3)

In [8]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[0. , 1. , 2. ],
        [3. , 4. , 5. ]]])

### Numpy sequences

In [9]:
from numpy import pi
x = np.linspace(0, pi/2, 7)
x

array([0.        , 0.26179939, 0.52359878, 0.78539816, 1.04719755,
       1.30899694, 1.57079633])

In [10]:
f = np.cos(x)
f

array([1.00000000e+00, 9.65925826e-01, 8.66025404e-01, 7.07106781e-01,
       5.00000000e-01, 2.58819045e-01, 6.12323400e-17])

### Some linear Algebra

In [11]:
from numpy import linalg as LA
A = np.arange(9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
print(np.linalg.det(A))
print(LA.matrix_rank(A))

0.0
2


In [13]:
w, v = LA.eig(A)
w

array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16])

In [14]:
A = A + np.eye(3, 3)
print(LA.matrix_rank(A))   # Full rank, hence invertible

3


In [15]:
b = np.array([1, 2, 5])
x = np.linalg.solve(A, b)  # A^{-1}b

np.matmul(A, x)            # Should give back b

array([1., 2., 5.])